<head>
    <!-- BEGIN META -->
     <meta charset="utf-8">
    <?php echo $this->headTitle('OpenPOI')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('keywords', 'your,keywords')
        ->appendName('description', 'Short explanation about this website')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- END META -->

    <!-- BEGIN STYLESHEETS -->
    <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->server('static') . '/img/favicon.ico'))
            ->prependStylesheet($this->server('static') . 'assets/css/theme-default/libs/morris/morris.core.css')
            ->prependStylesheet($this->server('static') . 'assets/css/theme-default/libs/rickshaw/rickshaw.css')
            ->prependStylesheet($this->server('static') . 'assets/css/theme-default/material-design-iconic-font.min.css')
            ->prependStylesheet($this->server('static') . 'assets/css/theme-default/font-awesome.min.css')
            ->prependStylesheet($this->server('static') . 'assets/css/theme-default/materialadmin.css')
            ->prependStylesheet($this->server('static') . 'assets/css/theme-default/bootstrap.css')
            ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900')
    ?>
    <!-- END STYLESHEETS -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script type="text/javascript" src="<?php echo $this->server('static')?>assets/js/libs/utils/html5shiv.js?1403934957"></script>
        <script type="text/javascript" src="<?php echo $this->server('static')?>assets/js/libs/utils/respond.min.js?1403934956"></script>
    <![endif]-->
    <script>
        var og = {};
        og.getStatic = '<?php echo $this->server('static') ?>';
        og.getContent = '<?php echo $this->server('content') ?>';
    </script>
</head>
