<!-- BEGIN MENUBAR-->
<div id="menubar" class="menubar-inverse ">
    <div class="menubar-fixed-panel">
        <div>
            <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                <i class="fa fa-bars"></i>
            </a>
        </div>
        <div class="expanded">
            <a href="../../html/dashboards/dashboard.html">
                <span class="text-lg text-bold text-primary ">MATERIAL&nbsp;ADMIN</span>
            </a>
        </div>
    </div>
    <div class="menubar-scroll-panel">
        
        <?php if(!empty($this->sysMenu)) { ?>
            <ul id="main-menu" class="gui-controls">
                <!-- BEGIN DASHBOARD -->
                <li>
                    <a href="/" class="<?php echo ($this->recurso['recurso'] == \Application\Entity\Functions::RECURSO_DEFAULT) ? 'active' : ''?>">
                        <div class="gui-icon"><i class="md md-home"></i></div>
                        <span class="title">Inicio</span>
                    </a>
                </li><!--end /menu-li -->
                <!-- END DASHBOARD -->
                <?php foreach ($this->sysMenu as $menu) { ?> 
                    <?php $css = ($this->recurso['controller'] == $menu['rec_uri']) ? 'active expanded' : ''?>
                    <li class="gui-folder <?php echo $css?>">
                        <a>
                            <div class="gui-icon"><i class="md <?php echo $menu['rec_css']?>"></i></div>
                            <span class="title"><?php echo $menu['rec_desc']?></span>
                        </a>
                        <!--start submenu -->
                        <?php if(!empty($menu['submenu'])) { ?>
                            <ul>
                                <?php foreach ($menu['submenu'] as $submenu) { ?> 
                                    <?php $cssSubmenu = ($this->recurso['recurso'] == $submenu['rec_uri']) ? 'active' : ''?>
                                    <li class="<?php echo $cssSubmenu?>">
                                        <a href="<?php echo $this->server('content') . $submenu['rec_link']?>" >
                                            <span class="title">
                                                <?php echo $submenu['rec_desc']?>
                                            </span>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                        <!--end /submenu -->
                    </li>
                <?php } ?>
            </ul><!--end .main-menu -->
            <!-- END MAIN MENU -->
        <?php } ?>


        <div class="menubar-foot-panel">
            <small class="no-linebreak hidden-folded">
                <span class="opacity-75">Copyright &copy; 2015</span> <strong>PerúCit</strong>
            </small>
        </div>
    </div><!--end .menubar-scroll-panel-->
</div><!--end #menubar-->
<!-- END MENUBAR -->