<?php $date = new \DateTime('NOW') ?>
<div style="padding: 10px; border: 1px solid #06C">
    <h1 style="color: #06C;"><img src="https://cdn1.iconfinder.com/data/icons/meBaze-Freebies/512/fixed-bug.png" width="25" heigth="25"/> Logical Exception </h1>
    <h3>Detail : </h3>
    <p><b>File :</b> <?php echo $this->exception->getFile() ?><p>
    <p><b>Line :</b> <?php echo $this->exception->getLine() ?><p>
    <p><b>Message : </b> <?php echo $this->exception->getMessage() ?><p><br/>
    <p><b><?php echo $date->format('Y-m-d h:i:s') ?></b></p>
</div>