<!-- BEGIN JAVASCRIPT -->
<?php
echo $this->headScript()
        ->prependFile($this->server('static') . 'assets/js/core/demo/Demo.js')
        ->prependFile($this->server('static') . 'assets/js/core/source/AppVendor.js')
        ->prependFile($this->server('static') . 'assets/js/core/source/AppNavSearch.js')
        ->prependFile($this->server('static') . 'assets/js/core/source/AppForm.js')
        ->prependFile($this->server('static') . 'assets/js/core/source/AppCard.js')
        ->prependFile($this->server('static') . 'assets/js/core/source/AppOffcanvas.js')
        ->prependFile($this->server('static') . 'assets/js/core/source/AppNavigation.js')
        ->prependFile($this->server('static') . 'assets/js/core/source/App.js')
        ->prependFile($this->server('static') . 'assets/js/libs/nanoscroller/jquery.nanoscroller.min.js')
        ->prependFile($this->server('static') . 'assets/js/libs/autosize/jquery.autosize.min.js')
        ->prependFile($this->server('static') . 'assets/js/libs/spin.js/spin.min.js')
        ->prependFile($this->server('static') . 'assets/js/libs/bootstrap/bootstrap.min.js')
        ->prependFile($this->server('static') . 'assets/js/libs/jquery/jquery-migrate-1.2.1.min.js')
?>
<!-- END JAVASCRIPT -->