<div class="img-backdrop" style="background-image: url('../../assets/img/img16.jpg')"></div>
<div class="spacer"></div>
<div class="card contain-sm style-transparent">
    <div class="card-body">
        <?php if(!empty($this->message)) { ?>
            <div class="row">
                <div class="col-sm-6">
                    <p><?php echo $this->message?><p>
                </div>
            </div>
        <?php } ?>
        <div class="row">
            <div class="col-sm-6">
                <br/>
                <span class="text-lg text-bold text-primary">Iniciar Sesión</span>
                <br/><br/>
                <form id="form-login" class="form floating-label" action="" accept-charset="utf-8" method="post">
                    <div class="form-group">
                        <?php echo $this->formRow($this->form->get('username'))?>
                        <label for="username">Usuario</label>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formRow($this->form->get('password'))?>
                        <label for="password">Contraseña</label>
                        <p class="help-block"><a href="#">Olvido su contraseña?</a></p>
                    </div>
                    <br/>
                    <div class="row">
                        <div class="col-xs-6 text-left">
                            <div class="checkbox checkbox-inline checkbox-styled">
<!--                                <label>
                                    <input type="checkbox"> <span>Remember me</span>
                                </label>-->
                            </div>
                        </div><!--end .col -->
                        <div class="col-xs-6 text-right">
                            <button class="btn btn-primary btn-raised" type="submit">Iniciar Sesión</button>
                        </div><!--end .col -->
                    </div><!--end .row -->
                </form>
            </div><!--end .col -->
            
        </div><!--end .row -->
    </div><!--end .card-body -->
</div><!--end .card -->

<script type="text/javascript">
    $(document).ready(function() {
        $('#form-login').validate({
            rules: {
                username: "required",
                password: "required"
            },messages: {
                'username' : 'Escriba su nombre de usuario',
                'password' : 'Escriba su contraseña.'
            }
        });
    });
</script>